export const FETCH_SIDEBAR_CATEGORY = "FETCH_SIDEBAR_CATEGORY";
export const SIDEBAR_CATEGORY_LOADING = "SIDEBAR_CATEGORY_LOADING";

export const FETCH_CAROUSEL_DATA = "FETCH_CAROUSEL_DATA";

export const FETCH_HOMEPRODUCTS = "FETCH_HOMEPRODUCTS";
export const HOMEPRODUCTS_LOADING= "HOMEPRODUCTS_LOADING";

export const FETCH_BANNER = "FETCH_BANNER";

export const UPDATE_CATEGORYNAME = "UPDATE_CATEGORY_NAME";
export const UPDATE_CATEGORYTYPE = "UPDATE_CATEGORY_TYPE";
